Repository lzaycoe/brainbox-frontend, pull requests merged in 2025-03, with the labels that each got.

#124 [FE] Integrate API Progress for UI Watch Course
  package.json
  pnpm-lock.yaml
  src/app/(learners)/layout.tsx
  src/app/(learners)/watch-course/[id]/page.tsx
  src/app/(learners)/watch-course/page.tsx
  src/app/layout.tsx
  src/app/teachers/courses/[id]/page.tsx
  src/app/teachers/create-course/page.tsx
  src/components/commons/Header.tsx
  src/components/commons/MenuItem.tsx
  src/components/commons/teachers/Header.tsx
  src/components/commons/teachers/SideBar.tsx
  src/components/learners/dashboard/CourseCard.tsx
  src/components/learners/watch-course/CommentSection.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/learners/watch-course/CourseNavigation.tsx
  src/components/learners/watch-course/CourseVideo.tsx
  src/components/learners/watch-course/Header.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/components/teachers/create-course/FormBasicInfo.tsx
  src/components/teachers/create-section/SectionTab.tsx
  src/config/.gitkeep
  src/config/categoryColors.ts
  src/config/menuItems.ts
  src/config/routerConfig.ts
  src/contexts/UserContext.tsx
  src/hooks/useUserMetadata.ts
  src/layouts/TeacherLayout.tsx
  src/middlewares/clerk-middleware.ts
  src/schemas/course.schema.ts
  src/schemas/lecture.schema.ts
  src/schemas/payment.schema.ts
  src/schemas/progress.schema.ts
  src/schemas/user.schema.ts
  src/services/api/course.ts
  src/services/api/lecture.ts
  src/services/api/payment.ts
  src/services/api/progress.ts
  src/services/api/user.ts
  src/services/custom/course/checkPayment.ts
  src/services/custom/course/fetchCourseData.ts
  src/services/custom/course/watchCourseServices.ts
  src/utils/date.ts
  src/utils/file.ts
Labels: enhancement

#125 Integrate API Progress for UI Watch Course
  package.json
  pnpm-lock.yaml
  src/app/(learners)/layout.tsx
  src/app/(learners)/watch-course/[id]/page.tsx
  src/app/(learners)/watch-course/page.tsx
  src/app/layout.tsx
  src/app/teachers/courses/[id]/page.tsx
  src/app/teachers/create-course/page.tsx
  src/components/commons/Header.tsx
  src/components/commons/MenuItem.tsx
  src/components/commons/teachers/Header.tsx
  src/components/commons/teachers/SideBar.tsx
  src/components/learners/dashboard/CourseCard.tsx
  src/components/learners/watch-course/CommentSection.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/learners/watch-course/CourseNavigation.tsx
  src/components/learners/watch-course/CourseVideo.tsx
  src/components/learners/watch-course/Header.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/components/teachers/create-course/FormBasicInfo.tsx
  src/components/teachers/create-section/SectionTab.tsx
  src/config/.gitkeep
  src/config/categoryColors.ts
  src/config/menuItems.ts
  src/config/routerConfig.ts
  src/contexts/UserContext.tsx
  src/hooks/useUserMetadata.ts
  src/layouts/TeacherLayout.tsx
  src/middlewares/clerk-middleware.ts
  src/schemas/course.schema.ts
  src/schemas/lecture.schema.ts
  src/schemas/payment.schema.ts
  src/schemas/progress.schema.ts
  src/schemas/user.schema.ts
  src/services/api/course.ts
  src/services/api/lecture.ts
  src/services/api/payment.ts
  src/services/api/progress.ts
  src/services/api/user.ts
  src/services/custom/course/checkPayment.ts
  src/services/custom/course/fetchCourseData.ts
  src/services/custom/course/watchCourseServices.ts
  src/utils/date.ts
  src/utils/file.ts
Labels: enhancement

#126 fix error display in course list learner
  src/components/learners/course-list/Course.tsx
Labels: bug

#131 [FE] Integrate API List Courses for UI Learner Dashboard & Learner Courses
  src/app/(learners)/courses/page.tsx
  src/app/(learners)/dashboard/page.tsx
  src/components/learners/courses/CourseList.tsx
  src/components/learners/dashboard/CoursesSection.tsx
  src/schemas/payment.schema.ts
  src/services/api/payment.ts
  src/services/custom/course/checkPayment.ts
  src/services/custom/course/checkProgress.ts
Labels: enhancement

#128 Feature/fix bug
  src/components/learners/course-list/Course.tsx
Labels: bug, good first issue

#134 Feature/task 79
  next.config.ts
  public/app/teacher/Card.png
  public/app/teacher/visa1.png
  public/app/teacher/visa2.png
  public/app/teacher/visa3.png
  src/app/teachers/earnings/page.tsx
  src/components/commons/teachers/RevenueChartCard.tsx
  src/components/teachers/earnings/CreditCard.tsx
  src/components/teachers/earnings/ListSummaryCard.tsx
  src/components/teachers/earnings/RevenueReport.tsx
  src/components/teachers/earnings/WithdrawHistory.tsx
  src/components/teachers/earnings/WithdrawMoney.tsx
  src/data/transactionsData.ts
Labels: enhancement

#129 [FE] Implement UI for Course detail integration API (get course)
  next.config.ts
  public/app/career/Career_01.png
  public/app/career/Career_02.png
  src/app/(learners)/career-detail/page.tsx
  src/app/(learners)/career/page.tsx
  src/app/(learners)/course-list/page.tsx
  src/app/(learners)/courses/[id]/page.tsx
  src/components/commons/CourseCard.tsx
  src/components/learners/career-detail/JobPosting.tsx
  src/components/learners/career/Content.tsx
  src/components/learners/career/Header.tsx
  src/components/learners/career/JobList.tsx
  src/components/learners/career/Logo.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/course/course-detail/CourseCard.tsx
  src/components/learners/courses/course/course-detail/CourseDetail.tsx
  src/components/learners/courses/course/course-detail/CourseHeader.tsx
  src/components/learners/courses/course/course-detail/CurriculumSection.tsx
  src/components/learners/courses/course/course-detail/InstructorSection.tsx
  src/components/learners/courses/course/course-detail/OverviewSection.tsx
  src/components/learners/courses/course/course-detail/RelatedCourses.tsx
  src/components/learners/courses/course/course-detail/ReviewSection.tsx
  src/components/learners/courses/course/course-detail/Tabs.tsx
  src/components/learners/courses/course/course-detail/VideoSection.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/home/ListCourseCardLandscape.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/settings/ProfilePhotoUploader.tsx
  src/components/learners/settings/ProfileSettings.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/schemas/lecture.schema.ts
  src/services/api/course.ts
  src/services/api/lecture.ts
Labels: enhancement

#139 [FE] Integrate API update course and lecture for teacher
  src/app/(learners)/watch-course/[id]/page.tsx
  src/app/teachers/courses/[id]/edit/page.tsx
  src/app/teachers/courses/[id]/page.tsx
  src/app/teachers/courses/[id]/sections/[section]/create-lecture/page.tsx
  src/app/teachers/courses/[id]/sections/[section]/lectures/[lecture]/edit/page.tsx
  src/app/teachers/courses/[id]/sections/page.tsx
  src/app/teachers/create-course/page.tsx
  src/components/commons/CourseCard.tsx
  src/components/commons/teachers/CourseForm.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/create-course/FormAdvanceInfo.tsx
  src/components/teachers/create-lecture/FormCreateLecture.tsx
  src/components/teachers/create-lecture/LectureTab.tsx
  src/services/api/course.ts
  src/services/api/lecture.ts
  src/services/supabase/delete.ts
  src/utils/currency.ts
Labels: enhancement

#143 Hotfix all bugs
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(learners)/course-list/page.tsx
  src/app/(learners)/layout.tsx
  src/app/globals.css
  src/app/teachers/courses/[id]/page.tsx
  src/components/commons/CourseCard.tsx
  src/components/commons/Loading.tsx
  src/components/commons/PaginationCustom.tsx
  src/components/commons/SearchAndFilter.tsx
  src/components/commons/teachers/CourseForm.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/course/course-detail/CourseCard.tsx
  src/components/learners/courses/course/course-detail/CourseDetail.tsx
  src/components/learners/courses/course/course-detail/CurriculumSection.tsx
  src/components/learners/courses/course/course-detail/OverviewSection.tsx
  src/components/learners/courses/course/course-detail/RelatedCourses.tsx
  src/components/learners/courses/course/course-detail/ThumbnailSection.tsx
  src/components/learners/home/Banner.tsx
  src/components/learners/home/BecomeTeacherSteps.tsx
  src/components/learners/home/BrowseCategories.tsx
  src/components/learners/home/CatergoryCard.tsx
  src/components/learners/home/CourseCardLandscape.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/home/ListCourseCardLandscape.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/home/TeacherCard.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/teachers/course-detail/CourseDetailCard.tsx
  src/components/teachers/course-detail/ListSummaryCard.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/components/teachers/setting/FormInfo.tsx
  src/components/ui/accordion.tsx
  src/config/categoryConfig.ts
  src/schemas/course.schema.ts
  src/schemas/lecture.schema.ts
  src/schemas/user.schema.ts
  src/services/api/lecture.ts
  src/services/api/payment.ts
  src/services/api/user.ts
  src/services/custom/user/getTotalStudentsForTeacher.ts
  src/utils/currency.ts
  tailwind.config.ts
Labels: bug

#147 Hotfix/fix all bugs
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(learners)/course-list/page.tsx
  src/app/(learners)/layout.tsx
  src/app/globals.css
  src/app/teachers/courses/[id]/page.tsx
  src/components/commons/CourseCard.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/Loading.tsx
  src/components/commons/PaginationCustom.tsx
  src/components/commons/SearchAndFilter.tsx
  src/components/commons/learners/Profile.tsx
  src/components/commons/teachers/CourseForm.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/course/course-detail/CourseCard.tsx
  src/components/learners/courses/course/course-detail/CourseDetail.tsx
  src/components/learners/courses/course/course-detail/CurriculumSection.tsx
  src/components/learners/courses/course/course-detail/OverviewSection.tsx
  src/components/learners/courses/course/course-detail/RelatedCourses.tsx
  src/components/learners/courses/course/course-detail/ThumbnailSection.tsx
  src/components/learners/home/Banner.tsx
  src/components/learners/home/BecomeTeacherSteps.tsx
  src/components/learners/home/BrowseCategories.tsx
  src/components/learners/home/CatergoryCard.tsx
  src/components/learners/home/CourseCardLandscape.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/home/ListCourseCardLandscape.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/home/TeacherCard.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/teachers/course-detail/CourseDetailCard.tsx
  src/components/teachers/course-detail/ListSummaryCard.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/components/teachers/setting/FormInfo.tsx
  src/components/ui/accordion.tsx
  src/config/categoryConfig.ts
  src/schemas/course.schema.ts
  src/schemas/lecture.schema.ts
  src/schemas/user.schema.ts
  src/services/api/lecture.ts
  src/services/api/payment.ts
  src/services/api/user.ts
  src/services/custom/user/getTotalStudentsForTeacher.ts
  src/utils/currency.ts
  tailwind.config.ts
Labels: bug, good first issue

#148 fix: fix error build
  src/components/learners/course-list/Course.tsx
  src/schemas/course.schema.ts
Labels: bug

#150 update: package version
  package.json
Labels: enhancement

#151 dev: release production v1.2.1
  package.json
  src/components/learners/course-list/Course.tsx
  src/schemas/course.schema.ts
Labels: bug, good first issue

#155 add: implement UI message learner
  src/app/(learners)/message/page.tsx
  src/app/teachers/message/page.tsx
  src/components/commons/learners/ChatMessage.tsx
  src/components/learners/message/ChatApp.tsx
  src/components/teachers/message/ChatApp.tsx
  src/data/messages.ts
Labels: enhancement

#160 Feature/task 157_ Message for teacher
  src/app/(learners)/message/page.tsx
  src/app/teachers/messages/page.tsx
  src/components/commons/learners/ChatMessage.tsx
  src/components/learners/message/ChatApp.tsx
  src/data/messages.ts
Labels: enhancement

#162 [FE] Integrate API update course and lecture for teacher
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(learners)/course-list/page.tsx
  src/app/(learners)/layout.tsx
  src/app/(learners)/watch-course/[id]/page.tsx
  src/app/globals.css
  src/app/teachers/courses/[id]/page.tsx
  src/app/teachers/courses/[id]/sections/[section]/lectures/[lecture]/edit/page.tsx
  src/app/teachers/courses/[id]/sections/page.tsx
  src/components/commons/CourseCard.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/Loading.tsx
  src/components/commons/PaginationCustom.tsx
  src/components/commons/SearchAndFilter.tsx
  src/components/commons/learners/Profile.tsx
  src/components/commons/teachers/CourseForm.tsx
  src/components/learners/checkout/id/Course.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/course/course-detail/CourseCard.tsx
  src/components/learners/courses/course/course-detail/CourseDetail.tsx
  src/components/learners/courses/course/course-detail/CurriculumSection.tsx
  src/components/learners/courses/course/course-detail/OverviewSection.tsx
  src/components/learners/courses/course/course-detail/RelatedCourses.tsx
  src/components/learners/courses/course/course-detail/ThumbnailSection.tsx
  src/components/learners/home/Banner.tsx
  src/components/learners/home/BecomeTeacherSteps.tsx
  src/components/learners/home/BrowseCategories.tsx
  src/components/learners/home/CatergoryCard.tsx
  src/components/learners/home/CourseCardLandscape.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/home/ListCourseCardLandscape.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/home/TeacherCard.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/teachers/course-detail/CourseDetailCard.tsx
  src/components/teachers/course-detail/ListSummaryCard.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/components/teachers/create-course/FormAdvanceInfo.tsx
  src/components/teachers/create-lecture/FileUploadInput.tsx
  src/components/teachers/create-lecture/FormCreateLecture.tsx
  src/components/teachers/setting/FormInfo.tsx
  src/components/ui/accordion.tsx
  src/config/categoryConfig.ts
  src/schemas/course.schema.ts
  src/schemas/lecture.schema.ts
  src/schemas/user.schema.ts
  src/services/api/lecture.ts
  src/services/api/payment.ts
  src/services/api/user.ts
  src/services/custom/user/getTotalStudentsForTeacher.ts
  src/utils/currency.ts
  tailwind.config.ts
Labels: enhancement

#161 [FE] Implement UI & Integrate API check courses for admin
  src/app/(learners)/message/page.tsx
  src/app/admins/check-courses/page.tsx
  src/app/teachers/messages/page.tsx
  src/components/admins/check-courses/CourseActionsDropdown.tsx
  src/components/admins/check-courses/CourseRequestTable.tsx
  src/components/admins/check-courses/StatusBadge.tsx
  src/components/commons/learners/ChatMessage.tsx
  src/components/learners/message/ChatApp.tsx
  src/data/messages.ts
Labels: enhancement

#170 fix: display paid courses for learner
  src/app/(learners)/courses/page.tsx
  src/app/(learners)/message/page.tsx
  src/app/(learners)/watch-course/[id]/page.tsx
  src/app/admins/dashboard/page.tsx
  src/app/admins/layout.tsx
  src/app/teachers/courses/[id]/sections/[section]/lectures/[lecture]/edit/page.tsx
  src/app/teachers/courses/[id]/sections/page.tsx
  src/app/teachers/messages/page.tsx
  src/components/admins/LoginForm.tsx
  src/components/commons/admins/Header.tsx
  src/components/commons/admins/SideBar.tsx
  src/components/commons/learners/ChatMessage.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/checkout/id/Course.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/CourseList.tsx
  src/components/learners/courses/course/course-detail/RelatedCourses.tsx
  src/components/learners/dashboard/CourseCard.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/message/ChatApp.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/teachers/create-course/FormAdvanceInfo.tsx
  src/components/teachers/create-lecture/FileUploadInput.tsx
  src/components/teachers/create-lecture/FormCreateLecture.tsx
  src/config/adminMenuItems.ts
  src/data/messages.ts
  src/layouts/AdminLayout.tsx
  src/schemas/course.schema.ts
  src/services/api/payment.ts
  src/services/custom/course/checkProgress.ts
  src/utils/adminInfo.ts
Labels: bug, enhancement

#173 fix display paid course for learner
  src/app/(learners)/courses/page.tsx
  src/app/(learners)/watch-course/[id]/page.tsx
  src/components/learners/courses/CourseList.tsx
  src/components/learners/dashboard/CourseCard.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/services/custom/course/checkProgress.ts
Labels: bug, enhancement

#172 [FE] Implement UI & Integrate API check courses for admin
  src/app/(learners)/watch-course/[id]/page.tsx
  src/app/admins/dashboard/page.tsx
  src/app/admins/layout.tsx
  src/app/teachers/courses/[id]/sections/[section]/lectures/[lecture]/edit/page.tsx
  src/app/teachers/courses/[id]/sections/page.tsx
  src/components/admins/LoginForm.tsx
  src/components/commons/admins/Header.tsx
  src/components/commons/admins/SideBar.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/checkout/id/Course.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/course/course-detail/RelatedCourses.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/components/teachers/create-course/FormAdvanceInfo.tsx
  src/components/teachers/create-lecture/FileUploadInput.tsx
  src/components/teachers/create-lecture/FormCreateLecture.tsx
  src/config/adminMenuItems.ts
  src/layouts/AdminLayout.tsx
  src/schemas/course.schema.ts
  src/services/api/payment.ts
  src/utils/adminInfo.ts
Labels: enhancement

#178 fix: add pattern for display image
  next.config.ts
Labels: bug, enhancement

#179 Hotfix/fix all bugs
  next.config.ts
Labels: bug, enhancement

#180 add: admin path
  next.config.ts
  package.json
  src/app/(learners)/become-teacher/page.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/learners/Profile.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/becomeATeacher/SectionSix.tsx
  src/components/learners/becomeATeacher/SectionTwo.tsx
  src/components/learners/dashboard/StatsSection.tsx
  src/components/learners/home/BecomeTeacherSteps.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/middlewares/clerk-middleware.ts
Labels: bug

#184 fix: increase video height in CourseVideo component
  src/components/learners/watch-course/CourseVideo.tsx
Labels: good first issue

#183 dev: release production v1.3.2
  next.config.ts
  package.json
  src/app/(learners)/become-teacher/page.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/learners/Profile.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/becomeATeacher/SectionSix.tsx
  src/components/learners/becomeATeacher/SectionTwo.tsx
  src/components/learners/dashboard/StatsSection.tsx
  src/components/learners/home/BecomeTeacherSteps.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/watch-course/CourseVideo.tsx
  src/middlewares/clerk-middleware.ts
Labels: good first issue

#186 Hotfix/fix all bugs
  package.json
  src/app/(learners)/course-list/page.tsx
  src/components/learners/course-list/Course.tsx
  src/components/teachers/courses/FilterSelects.tsx
Labels: bug, enhancement

#182 dev: merge code from main
  next.config.ts
  package.json
  src/app/(learners)/become-teacher/page.tsx
  src/app/(learners)/course-list/page.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/learners/Profile.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/becomeATeacher/SectionSix.tsx
  src/components/learners/becomeATeacher/SectionTwo.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/dashboard/StatsSection.tsx
  src/components/learners/home/BecomeTeacherSteps.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/watch-course/CourseVideo.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/middlewares/clerk-middleware.ts
Labels: good first issue

#193 [FE] Implement UI & Integrate API for Category
  src/app/(learners)/category/page.tsx
  src/components/learners/category/ListCourseByCategory.tsx
  src/components/learners/category/ListTeacherByCategory.tsx
  src/components/learners/home/BrowseCategories.tsx
Labels: enhancement

#188 Feature/task 167 linh
  src/app/(learners)/courses/page.tsx
  src/app/(learners)/dashboard/page.tsx
  src/app/(learners)/teacher/page.tsx
  src/components/commons/SearchAndFilter.tsx
  src/components/commons/learners/NavigationBar.tsx
  src/components/commons/learners/Profile.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/CourseList.tsx
  src/components/learners/dashboard/CoursesSection.tsx
  src/components/learners/dashboard/StatsSection.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/learners/settings/ProfileForm.tsx
  src/components/learners/settings/ProfilePhotoUploader.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/services/api/progress.ts
Labels: enhancement

#196 Feature/task 167
  src/app/(learners)/courses/page.tsx
  src/app/(learners)/dashboard/page.tsx
  src/app/(learners)/teacher/page.tsx
  src/components/commons/SearchAndFilter.tsx
  src/components/commons/learners/NavigationBar.tsx
  src/components/commons/learners/Profile.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/CourseList.tsx
  src/components/learners/dashboard/CoursesSection.tsx
  src/components/learners/dashboard/StatsSection.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/learners/settings/ProfileForm.tsx
  src/components/learners/settings/ProfilePhotoUploader.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/services/api/progress.ts
Labels: enhancement

#197 [FE] Implement UI & Integrate API for Category
  src/app/(learners)/category/page.tsx
  src/components/learners/category/ListCourseByCategory.tsx
  src/components/learners/category/ListTeacherByCategory.tsx
  src/components/learners/home/BrowseCategories.tsx
Labels: enhancement

#192 [FE] Implement UI for Teacher my course detail
  src/app/admins/dashboard/page.tsx
  src/app/teachers/courses/[id]/page.tsx
  src/app/teachers/dashboard/page.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/learners/watch-course/CourseNavigation.tsx
  src/components/learners/watch-course/CourseVideo.tsx
  src/components/teachers/course-detail/CourseDetail.tsx
  src/components/teachers/dashboard/ListSummaryCardDashboard.tsx
  src/services/custom/course/watchCourseServices.ts
Labels: enhancement

#198 Feature/task 189
  src/app/admins/dashboard/page.tsx
  src/app/teachers/courses/[id]/page.tsx
  src/app/teachers/dashboard/page.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/learners/watch-course/CourseNavigation.tsx
  src/components/learners/watch-course/CourseVideo.tsx
  src/components/teachers/course-detail/CourseDetail.tsx
  src/components/teachers/dashboard/ListSummaryCardDashboard.tsx
  src/services/custom/course/watchCourseServices.ts
Labels: enhancement

#200 [FE] Implement UI & Integrate API for handle salary of teacher for admin
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/admins/layout.tsx
  src/app/admins/withdraw-requests/page.tsx
  src/components/admins/withdraw-requests/Columns.tsx
  src/components/admins/withdraw-requests/DataTable.tsx
  src/components/admins/withdraw-requests/WithdrawActionsCell.tsx
  src/components/commons/Loading.tsx
  src/components/teachers/course-detail/CourseDetail.tsx
  src/components/teachers/earnings/BankAccountForm.tsx
  src/components/teachers/earnings/CreditCard.tsx
  src/components/teachers/earnings/CustomBankCard.tsx
  src/components/teachers/earnings/ListSummaryCard.tsx
  src/components/teachers/earnings/WithdrawHistory.tsx
  src/components/teachers/earnings/WithdrawMoney.tsx
  src/components/ui/badge.tsx
  src/components/ui/command.tsx
  src/components/ui/drawer.tsx
  src/components/ui/popover.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/sheet.tsx
  src/components/ui/table.tsx
  src/config/adminMenuItems.ts
  src/config/allowedHostnames.ts
  src/data/transactionsData.ts
  src/hooks/useUserMetadata.ts
  src/layouts/AdminLayout.tsx
  src/schemas/bank.schema.ts
  src/schemas/revenue.schema.ts
  src/schemas/user.schema.ts
  src/schemas/withdraw.schema.ts
  src/services/api/bank.ts
  src/services/api/revenue.ts
  src/services/api/user.ts
  src/services/api/withdraw.ts
  src/services/custom/course/watchCourseServices.ts
  src/services/custom/user/getTeacherBankAccount.ts
  src/services/custom/withdraw/getWithdrawHistory.ts
  src/types/withdrawRequest.ts
  src/utils/date.ts
  src/utils/handleWithdrawRequest.ts
Labels: enhancement

#203 [FE] Implement UI & Integrate API check courses for admin
  README.md
  next.config.ts
  package.json
  src/app/(learners)/become-teacher/page.tsx
  src/app/(learners)/category/page.tsx
  src/app/(learners)/course-list/page.tsx
  src/app/(learners)/courses/[id]/page.tsx
  src/app/(learners)/courses/page.tsx
  src/app/(learners)/dashboard/page.tsx
  src/app/(learners)/teacher/page.tsx
  src/app/(learners)/watch-course/[id]/page.tsx
  src/app/admins/check-courses/course/[id]/page.tsx
  src/app/admins/dashboard/page.tsx
  src/app/teachers/courses/[id]/page.tsx
  src/app/teachers/dashboard/page.tsx
  src/components/admins/check-courses/CourseRequestTable.tsx
  src/components/commons/Footer.tsx
  src/components/commons/Header.tsx
  src/components/commons/SearchAndFilter.tsx
  src/components/commons/learners/NavigationBar.tsx
  src/components/commons/learners/Profile.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/becomeATeacher/SectionSix.tsx
  src/components/learners/becomeATeacher/SectionTwo.tsx
  src/components/learners/category/ListCourseByCategory.tsx
  src/components/learners/category/ListTeacherByCategory.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/courses/CourseList.tsx
  src/components/learners/courses/course/course-detail/CourseDetail.tsx
  src/components/learners/dashboard/CourseCard.tsx
  src/components/learners/dashboard/CoursesSection.tsx
  src/components/learners/dashboard/StatsSection.tsx
  src/components/learners/home/BecomeTeacherSteps.tsx
  src/components/learners/home/BrowseCategories.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/purchase-history/Content.tsx
  src/components/learners/settings/ProfileForm.tsx
  src/components/learners/settings/ProfilePhotoUploader.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/learners/watch-course/CourseNavigation.tsx
  src/components/learners/watch-course/CourseVideo.tsx
  src/components/teachers/course-detail/CourseDetail.tsx
  src/components/teachers/course-detail/CourseDetailCard.tsx
  src/components/teachers/courses/FilterSelects.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/components/teachers/dashboard/ListSummaryCardDashboard.tsx
  src/middlewares/clerk-middleware.ts
  src/services/api/course.ts
  src/services/api/progress.ts
  src/services/custom/course/checkProgress.ts
  src/services/custom/course/watchCourseServices.ts
Labels: enhancement

#204 [FE] Implement UI & Integrate API check courses for admin
  src/app/(learners)/courses/[id]/page.tsx
  src/app/admins/check-courses/course/[id]/page.tsx
  src/app/teachers/courses/[id]/page.tsx
  src/components/admins/check-courses/CourseRequestTable.tsx
  src/components/learners/courses/course/course-detail/CourseDetail.tsx
  src/components/learners/watch-course/CourseMenu.tsx
  src/components/teachers/course-detail/CourseDetail.tsx
  src/components/teachers/course-detail/CourseDetailCard.tsx
  src/components/teachers/courses/TeacherCourseList.tsx
  src/services/api/course.ts
  src/services/custom/course/watchCourseServices.ts
Labels: enhancement

#208 hotfix: error deployment
  CONTRIBUTING.md
  src/components/learners/courses/CourseList.tsx
  src/components/learners/dashboard/CoursesSection.tsx
Labels: bug

#209 hotfix: error deployment
  CONTRIBUTING.md
  src/components/learners/courses/CourseList.tsx
  src/components/learners/dashboard/CoursesSection.tsx
Labels: bug

#211 Hotfix/fix all bugs chuong
  package.json
  src/app/(learners)/course-list/page.tsx
  src/app/admins/dashboard/page.tsx
  src/app/teachers/dashboard/metadata.ts
  src/app/teachers/dashboard/page.tsx
  src/components/admins/LoginForm.tsx
  src/components/admins/dashboard/ListSummaryCardDashboard.tsx
  src/components/commons/CourseCard.tsx
  src/components/commons/Header.tsx
  src/components/commons/admins/Header.tsx
  src/components/commons/teachers/Header.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/home/TeacherCard.tsx
  src/components/teachers/dashboard/ListSummaryCardDashboard.tsx
  src/components/teachers/dashboard/RevenueReport.tsx
  src/schemas/revenue.schema.ts
  src/services/api/revenue.ts
Labels: bug, good first issue

#212 update: release version 1.4.1
  package.json
  src/app/(learners)/course-list/page.tsx
  src/app/admins/dashboard/page.tsx
  src/app/teachers/dashboard/metadata.ts
  src/app/teachers/dashboard/page.tsx
  src/components/admins/LoginForm.tsx
  src/components/admins/check-courses/CourseRequestTable.tsx
  src/components/admins/dashboard/ListSummaryCardDashboard.tsx
  src/components/commons/CourseCard.tsx
  src/components/commons/Header.tsx
  src/components/commons/admins/Header.tsx
  src/components/commons/teachers/Header.tsx
  src/components/learners/becomeATeacher/InstructorSection.tsx
  src/components/learners/course-list/Course.tsx
  src/components/learners/home/ListCourseCard.tsx
  src/components/learners/home/ListTeacherCard.tsx
  src/components/learners/home/TeacherCard.tsx
  src/components/teachers/course-detail/CourseDetail.tsx
  src/components/teachers/dashboard/ListSummaryCardDashboard.tsx
  src/components/teachers/dashboard/RevenueReport.tsx
  src/schemas/revenue.schema.ts
  src/services/api/revenue.ts
  src/services/custom/course/fetchCourseData.ts
Labels: good first issue
